# Song class has title, artist_name, and youtube_url

import song

TOP_TEN_SONGS = [
    song.Song(title="Ric Flair Drip",
                artist_name="21 Savage, Offset, Metro Boomin",
                artist_picture="21savage.jpg",
                youtube_url="https://www.youtube.com/embed/LPTlvQ1Zet0"),
    song.Song(title="OTW",
                artist_name="Khalid ft. 6LACK, Ty Dolla $ign",
                artist_picture="khalid.jpg",
                youtube_url="https://www.youtube.com/embed/hjf-h6NMj7U"),
    song.Song(title="Kevin's Heart",
                artist_name="J. Cole",
                artist_picture="jcole.jpg",
                youtube_url="https://www.youtube.com/embed/ufynqs_COF4"),
    song.Song(title="Guatemala",
                artist_name="Swae Lee ft. Slim Jxmmi, Rae Sremmurd",
                artist_picture="swaelee.jpg",
                youtube_url="https://www.youtube.com/embed/1zXOcXnD8XU"),
    song.Song(title="Walk It Talk It",
                artist_name="Migos ft. Drake",
                artist_picture="migos.jpg",
                youtube_url="https://www.youtube.com/embed/fGqdIPer-ms"),
    song.Song(title="CLOSE",
                artist_name="Rae Sremmurd ft. Travis Scott",
                artist_picture="raesremmurd.jpg",
                youtube_url="https://www.youtube.com/embed/-wo8HsrmYvU"),
    song.Song(title="Produced by Blocboy",
                artist_name="BlocBoy JB",
                artist_picture="blocboyjb.jpg",
                youtube_url="https://www.youtube.com/embed/eNcxnKs4OeY"),
    song.Song(title="Bust Down",
                artist_name="Trippie Redd",
                artist_picture="trippieredd.jpg",
                youtube_url="https://www.youtube.com/embed/J8Mg5d8qz4M"),
    song.Song(title="Drama",
                artist_name="Roy Woods ft. Drake",
                artist_picture="roywoods.jpg",
                youtube_url="https://www.youtube.com/embed/XP0fdtXn49s"),
    song.Song(title="Freak In You",
                artist_name="Drake",
                artist_picture="drake.jpg",
                youtube_url="https://www.youtube.com/embed/-uCBZqVNpB4")
                ]

