import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='AP Government',
                  teacher_name='Mr. Capitan',
                  resource_name='History.org',
                  resource_url='http://www.history.org/'),
    course.Course(period=3,
                  name='Jazz Band',
                  teacher_name='Mr. Talbert',
                  resource_name='What is Jazz?',
                  resource_url='americanhistory.si.edu/smithsonian-jazz/education/what-jazz'),
    course.Course(period=4,
                  name='ASB',
                  teacher_name='Ms. Nelson',
                  resource_name='SSFHS ASB',
                  resource_url='http://ssfhs.schoolloop.com/WhoisASB'),
    course.Course(period=5,
                  name='Spanish 2',
                  teacher_name='Ms. Geiser',
                  resource_name='Wikipedia',
                  resource_url='https://en.wikipedia.org/wiki/Spanish_language'),
    course.Course(period=6,
                  name='ERWC',
                  teacher_name='Ms. Wenzell',
                  resource_name='Dictionary',
                  resource_url='https://www.dictionary.com')]

# Song class has title, artist_name, and youtube_url

import song

TOP_TEN_SONGS = [
    song.Song(title="Ric Flair Drip",
                artist_name="21 Savage, Offset, Metro Boomin",
                youtube_url="https://www.youtube.com/embed/LPTlvQ1Zet0"),
    song.Song(title="OTW",
                artist_name="Khalid ft. 6LACK, Ty Dolla $ign",
                youtube_url="https://www.youtube.com/embed/hjf-h6NMj7U"),
    song.Song(title="Kevin's Heart",
                artist_name="J. Cole",
                youtube_url="https://www.youtube.com/embed/ufynqs_COF4"),
    song.Song(title="Guatemala",
                artist_name="Swae Lee ft. Slim Jxmmi, Rae Sremmurd",
                youtube_url="https://www.youtube.com/embed/1zXOcXnD8XU"),
    song.Song(title="Walk It Talk It",
                artist_name="Migos ft. Drake",
                youtube_url="https://www.youtube.com/embed/fGqdIPer-ms"),
    song.Song(title="CLOSE",
                artist_name="Rae Sremmurd ft. Travis Scott",
                youtube_url="https://www.youtube.com/embed/-wo8HsrmYvU"),
    song.Song(title="Produced by Blocboy",
                artist_name="BlocBoy JB",
                youtube_url="https://www.youtube.com/embed/eNcxnKs4OeY"),
    song.Song(title="Bust Down",
                artist_name="Trippie Redd",
                youtube_url="https://www.youtube.com/embed/J8Mg5d8qz4M"),
    song.Song(title="Drama",
                artist_name="Roy Woods ft. Drake",
                youtube_url="https://www.youtube.com/embed/XP0fdtXn49s"),
    song.Song(title="Freak In You",
                artist_name="Drake",
                youtube_url="https://www.youtube.com/embed/-uCBZqVNpB4")
                ]

